version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.2-stretch
    steps:
      - checkout
      - run:
          name: "Install AWS Cli & Zappa"
          command: sudo pip install awscli zappa
      - run:
          name: "Install Dependencies"
          command: pipenv install
      - run:
          name: "Deploy Flask Application"
          command: bash ./.circleci/deploy.sh

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy
